const products = [
  {
    id: "shoe",
    key: "1",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899,
    deci: "00",
    slug: "/product/shoe1",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "2",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1249,
    deci: "00",
    slug: "/product/shoe2",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "3",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 499,
    deci: "00",
    slug: "/product/shoe3",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "4",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 779,
    deci: "00",
    slug: "/product/shoe4",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 2999,
    deci: "00",
    slug: "/product/shoe5",
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1899,
    deci: "00",
    slug: "/product/shoe6",
    review: 124,
    purchased: 567,
  },
];

export default products;
