const products = [
  {
    id: "shoe",
    key: "1",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899,
    deci: "00",
    slug: ["shoe1"],
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "2",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 1249,
    deci: "00",
    slug: ["shoe2"],
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "3",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 499,
    deci: "00",
    slug: ["shoe3"],
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "4",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae, maxime.",
    img: "/shoe.jpg",
    category: "shoe",
    price: 779,
    deci: "00",
    slug: ["shoe4"],
    review: 124,
    purchased: 567,
  },
];

export default products;
