products = [
  {
    id: "shoe",
    key: "1",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "2",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "3",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "4",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "5",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
  {
    id: "shoe",
    key: "6",
    name: "shoe",
    img: "/shoe.jpg",
    category: "shoe",
    price: 899.0,
    review: 124,
    purchased: 567,
  },
];

export default products;
